[build]
  publish = "."
  command = "echo 'No build step needed'"

[build.environment]
  NODE_VERSION = "18"

# Otimização de imagens
[[headers]]
  for = "/Images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Encoding = "gzip"

# Otimização de áudio
[[headers]]
  for = "/Audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    Content-Encoding = "gzip"

# Headers específicos para MP3
[[headers]]
  for = "/Audio/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"
    Accept-Ranges = "bytes"
    X-Content-Type-Options = "nosniff"

# Compressão geral
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"
